### ISSUE TITLE
confused about what redot is

### ISSUE THREAD

**Issue by hexxt-git** [Redot-Engine/redot-docs#10]
this redot fork has a really nice name and logo. it is flashy and exciting but i can't find anywhere what it is supposed to be (other than a godot fork of course)

so i have a few questions
- will the fork have any additional features
- will it fix engine bugs
- will it keep pulling changes from the original repository
- is there a roadmap for where you want to take this

if your issues are with the twitter/discord server why wouldn't you demand the people in charge change

i think this movement will both waste a lot of people time and eventually fail due to the lack of actual of developers and a goal even

you might as-well made a theme for godot and saved the twitter check mark subscription cost if you can't answer

**Comment by SkogiB** [comment]
1) Yes, as long as we can keep compatibility with Godot for a while first
2) Yes, some are already in the pipeline for years old bugs in Godot
3) Yes, we must in order to not fall behind with a small dev team
4) Yes, but we need a stable build first

I wish just demanding change from leadership worked, but the reality is that the leadership does not care and they have established a "cult" as some call it around themselves which shouts down and browbeats dissenters into silence. It is simply not a tenable arrangement.

Lemme know if you have more questions
